xms_app: "Xms512M"
xmx_app: "Xmx1024M"
premsize_app: "XX:MaxMetaspaceSize=150M"
heapdump_app: "XX:+HeapDumpOnOutOfMemoryError"
heapdumppath_app: "XX:HeapDumpPath=/msservice/data"
truststore:
gc:
clienttimeout:
dt_ci: MPRD
dt_env: A
optional_profiles: ",fatjar"