---
- name: Configure FluentD msps
  vars_files:
    - /msservice/bin/ansible/hosts/UAT/servers.yml
  hosts: all-vms
  serial: 1
  roles:
   - {
        role: configure_fluentd_agent,
        dynamic_config_file: "td-agent-msps.conf"
     }
