xms_app: "Xms1024M"
xmx_app: "Xmx2048M"
premsize_app: "XX:MaxPermSize=256M"
heapdump_app: "XX:+HeapDumpOnOutOfMemoryError"
heapdumppath_app: "XX:HeapDumpPath=/msservice/data"
truststore:
gc:
clienttimeout:
port: 
dt_ci: "CPV"
dt_env : "P"
optional_profiles: ",fatjar"
