---
- name: Configure FluentD msps
  vars_files:
    - /msservice/bin/ansible/vars/DR/instances-vars.yml
  hosts: fluentd-dr
  serial: 1
  roles:
   - {
        role: configure_fluentd_agent,
        dynamic_config_file: "td-agent-dr-msps.conf"
     }
