---
 - hosts: '{{ appcode }}-{{ env }}'

   vars_files:
    - /msservice/bin/ansible/vars/vars.yml
    - /msservice/bin/ansible/vars/PRD/apps/{{ appcode }}.yml

   any_errors_fatal: true
   serial: 1
   tasks:
     - name: Checking..................
       local_action: stat path={{dir_release}}/{{appcode}}-{{version}}.jar
       register: result
     - name: Check the ear file
       fail: msg="ear file doesn't exist"
       when: not result.stat.exists
       ignore_errors: yes
     - name: Checking..................
       stat: path={{dir_pid}}/{{appcode}}.pid
       register: res
     - name: Remove current application deployed on host
       shell: PID=`cat {{dir_pid}}/{{appcode}}.pid` && kill -9 $PID ; rm {{dir_pid}}/{{appcode}}.pid
       when: res.stat.exists
       ignore_errors: yes
     - name: Checking..................
       stat: path={{dir_deploy}}{{appcode}}*.jar
       register: rest
     - name: Preparing deploymet folder
       shell: rm -f {{dir_deploy}}*.jar
     - name: copy file if it exists
       copy: src={{dir_release}}/{{appcode}}-{{version}}.jar dest={{dir_deploy}}
       when: result.stat.exists
     - name: Log stat
       stat: path={{dir_log}}/{{appcode}}.log
       register: log_stat
     - name: Log rotate
       shell: mv {{dir_log}}/{{appcode}}.log {{dir_log}}/{{appcode}}.log.$(date +%F-%H:%M).log
       when: log_stat.stat.exists
     - name: Deploy jar file with DTM
       shell: if [ -f /opt/dynatrace/agent/lib/liboneagentproc.so ] ; then LD_PRELOAD=liboneagentproc.so && DT_CUSTOM_PROP="CI_NAME={{dt_ci}} ENVIRONMENT={{dt_env}} LD_PRELOAD=liboneagentproc.so" && export LD_PRELOAD && export DT_CUSTOM_PROP ; fi ; nohup /usr/bin/java -server -{{xms_app}} -{{xmx_app}} -{{premsize_app}} -{{heapdump_app}} -{{heapdumppath_app}} -Dspring.profiles.active={{env}}{{optional_profiles}} {{optional_vm_args}} {{truststore}} -jar {{dir_deploy}}{{appcode}}-{{version}}.jar & echo $! > {{dir_pid}}/{{appcode}}.pid
       ignore_errors: yes
#     - name: Waiting for Startup
#       pause: seconds=70
#     - name: Test
#       command: curl --head --silent http://{{ansible_hostname}}:{{port}}/{{appcode}}/
#       register: statuscode
#     - name: Result Test
#       debug: msg="test is ok"
#       when: statuscode.stdout.find("200 OK") != -1

